### ISSUE TITLE
设置优先级问题

### ISSUE THREAD

**Issue by xumingxin7398** [DTFE/vimo#11]
Navbar组件尽管在页面中设置了`<Navbar :hideBackButton="true">`在路由存在返回时仍会显示backButton
Tabs组件尽管在app-configs中设置了android: {mode: 'ios'}同时在页面中设置了`<Tabs mode="ios">`在安卓设备上仍显示md风格的样式

**Comment by xiangsongtao** [comment]
第一个设置hideBackButton的问题应该是好了

**Comment by xiangsongtao** [comment]
目前存在的问题是, 外部定义的mode类型未在内部比如Icon和Badge中生效, 这个问题已修复, 现在: Tabs和Tab两个组件的mode根据业务需要分来定义

**Comment by xiangsongtao** [comment]
"Tabs组件尽管在app-configs中设置了android: {mode: 'ios'}", 这个问题未复现
