### ISSUE TITLE
recordPosition在页面中存在v-for动态元素时无效

### ISSUE THREAD

**Issue by xumingxin7398** [DTFE/vimo#12]
页面中存在v-for动态加载(远程请求)的元素时，recordPosition都不能滚动到原先的位置，另外，recordPosition还原的位置与原先记录的滚动位置不一样，比如原先记录的位置是282，还原后却只滚动到182。

**Comment by xumingxin7398** [comment]
补充另外一个问题，当使用`<keep-alive><router-view></router-view></keep-alive>`来缓存页面渲染的时候，recordPosition将完全失效。

**Comment by xiangsongtao** [comment]
目前, 只对固定内容的情况适用record-position, 但是异步的过程这有点捉急, 因为异步完成数据的时机无法确定, 数据量也无法确定, 额, 你有好的方案吗?

**Comment by xiangsongtao** [comment]
如果要保持异步的页面也能记住滚动位置, 那就使用keep-alive吧, 这个我测试了能保留浏览位置.
