### ISSUE TITLE
Modal等组件无法访问$parent或$router

### ISSUE THREAD

**Issue by xumingxin7398** [DTFE/vimo#13]
需求是需要在Modal组件中进行页面跳转动作，此时在Modal中却无法获取$parent或$router。尝试通过自定义eventBus来$emit事件后，由父页面进行跳转，然而延时很高，必须等到Modal关闭，并停留在父页面近1秒后才跳转。求一个可行的解决方案，解决从Modal组件中进行路由跳转的问题。

**Comment by xiangsongtao** [comment]
1. 建议H5在同一时间只做一个动画，Modal关闭之后进行页面跳转
2. 目前在modal中是无法获取**父组件/根组件/上一页面**实例的, 可以在Modal的data中传入Modal需要的数据(比如上一个页面的$context/$router等)
3. 我写了一个demo, CI完毕后, 地址我再补上

**Comment by xiangsongtao** [comment]
vimo引入组件的方式有些变更, 你看下这个代码也许能帮上忙, 主要是import方式, 之前是```import {Button} from 'vimo/lib/button'```, 改为了 ```import Button from 'vimo/lib/button'```. 变更的组件范围[参考这里](https://github.com/DTFE/vimo/blob/master/components/dist.js). 
或者根据错误提示也能很快修正.
