### ISSUE TITLE
图片预览组件的缩放问题

### ISSUE THREAD

**Issue by xumingxin7398** [DTFE/vimo#14]
图片预览组件，放大图片后再缩到比原比例小时，图片的位置发生了变化，另外图片的缩放不太顺畅。

**Comment by xiangsongtao** [comment]
不确定你运行的平台是什么, 原生H5实现的图片预览组件(里面的轮播使用的是Swiper)没发现你说的问题. r线上的DEMO如果是在支付宝中则运行时的支付宝提供的组件, 好像也没你说的问题.

**Comment by xumingxin7398** [comment]
android多款手机，微信平台：问题如下：
原图：
![image](https://user-images.githubusercontent.com/7893611/31872366-f98689d0-b7ed-11e7-9ad8-c8d5350954a7.png)
问题：
![image](https://user-images.githubusercontent.com/7893611/31872359-ef598b42-b7ed-11e7-805c-570834bf6818.png)
操作：先拉伸放大图片，然后选择图片角落的两点来缩小图片，会出现图片不居中，显示确实，甚至不显示的情况。
