### ISSUE TITLE
路由开启keep-alive时，页面title不变化

### ISSUE THREAD

**Issue by xumingxin7398** [DTFE/vimo#15]
问题类似于[http://www.jianshu.com/p/42429f4d8f9e](url)第6点

**Comment by xiangsongtao** [comment]
keepalive的模式类似于App导航, 页面会常驻内存, 只有在触发activated钩子才更新页面内容.
当初, VImo这套不适合使用keepalive机制的, 因为activated这套机制只在route页面才起作用, 页面内部的组件是无法感知keepalive的(vue2.20之前), 在 2.2.0 及其更高版本可以, 这部分我整理下, 目前建议关闭keepalive功能

**Comment by xiangsongtao** [comment]
Title的问题已更新, Navbar也有同样的问题, 稍微有点麻烦, 稍后修复.
