### ISSUE TITLE
微信中页面无法向上滚动

### ISSUE THREAD

**Issue by xumingxin7398** [DTFE/vimo#16]
微信中向上滚动体验极差，几乎无法滚动，可以用微信扫描vimo-demo进行体验。

**Comment by xiangsongtao** [comment]
@xumingxin7398 你是指在Content组件中的内容上下滚动体验差?还是滚动到顶部这个效果?

**Comment by xiangsongtao** [comment]
@xumingxin7398 能提供下有问题的机型吗?

**Comment by xiangsongtao** [comment]
Content组件是使用的固定高度, 内容通过```overflow-y:scroll;```滚动的, 极限条件下(整个view拖动的效果,时内容无法滚动)会有问题.

**Comment by xiangsongtao** [comment]
Content组件是使用的固定高度, 内容通过```overflow-y:scroll;```滚动的, 极限条件下(整个view拖动的效果,时内容无法滚动)会有问题.

**Comment by xumingxin7398** [comment]
一加2手机有问题，是指整个页面的内容上下滚动，经测试，苹果手机和部分安卓手机没有出现类似问题。

**Comment by xiangsongtao** [comment]
@xumingxin7398 一加2手机在自带的浏览器中使用有问题吗? 是不是微信版本的问题? 我觉得 问题点是一加2手机微信浏览器对overflow:scroll的支持不够好, 解决办法使用js模拟滚动实现: better-scroll/iscroll, 或者使用vimo的Scroll组件, 需要将Scroll组件fix到页面中, 内容填充到Scroll里面. (这是我不想看到的结果) 
demo: https://dtfe.github.io/vimo/component-Scroll.html

**Comment by xumingxin7398** [comment]
一加2手机中的微信6.5.16的浏览器有问题，猜测是微信中下拉会触发显示"网页由xxx提供"的头部，造成事件冲突导致，在一加2的原生浏览器中没有问题，这个问题可能是better-scroll的问题，谢谢耐心解答。

**Comment by xiangsongtao** [comment]
@xumingxin7398 Github首页中有我的主页地址, 主页中有联系方式, 如果问题紧急的话.
